kind: pipeline
name: maven 构建 java 项目

steps:
  - name: Maven 编译
    image: maven:3.6.2-jdk-8
    volumes:
      - name: cache
        path: /root/.m2
    commands:
      - mvn clean install
    when:
      branch: master
      event: [ push ]

#  - name: send-wechat
#      image: yakumioto/serverchan
#      settings:
#        key: SCU65337T9a3aabd69bff82c132da7db6c743dad85db8d23dd7d06
#        text: drone 通知
#        desp: 项目 drone java demo构建成功
